package inheritance;
class ParentL{
	ParentL(){
		System.out.println("parent 0 arg cons");}
}

 class ChildL extends ParentL { //kittttttttttt//
/*code is generated by compiler
 * Child(){}
 * super();
	*/
	public static void main(String[] args) {
		
new ChildL();
	}

}
