package inheritance;
class ParentQ{
	ParentQ(){
		System.out.println("parent class cons 0 arg");    
		}
	{  
		System.out.println("parent class instance block"); 
	}
}

public class Instance2 extends ParentQ  {
	Instance2(){
		//super(); generated by compiler //
		System.out.println("child class cons 0 args");
	}
	{
		System.out.println("child class instance block");
	}
	

	public static void main(String[] args) {
		new Instance2();
	}

}
